# Generated by Django 4.0.6 on 2022-07-22 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='sub_content',
            field=models.TextField(default='It is sub-content of this post'),
            preserve_default=False,
        ),
    ]
